# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigoMateria', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=60)),
                ('unidadesCredito', models.IntegerField()),
                ('area', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigoDepartamento', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigoPrograma', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePrograma', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedulaIdentidad', models.IntegerField(primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=15)),
                ('segundoNombre', models.CharField(max_length=15, null=True)),
                ('primerApellido', models.CharField(max_length=15)),
                ('segundoApellido', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('rol', models.CharField(default='', max_length=25)),
                ('codigoDepartamento1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Departamento'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='programaPertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Programa'),
        ),
    ]
