# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigoMateria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=60)),
                ('unidadesCredito', models.IntegerField()),
                ('area', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigoDepartamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('codigoMaestria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreMaestria', models.CharField(max_length=60)),
                ('codigoDepartamentoPertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigoRol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedulaIdentidad', models.IntegerField(primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=15)),
                ('segundoNombre', models.CharField(max_length=15, null=True)),
                ('primerApellido', models.CharField(max_length=15)),
                ('segundoApellido', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('codigoDepartamento1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Departamento')),
                ('rol1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='maestriaPertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Maestria'),
        ),
    ]
