CREATE TABLE ASIGNATURA(
COD_ASIG					      VARCHAR(12) PRIMARY KEY,
ASIG_NOMBRE					    VARCHAR(40) NOT NULL, 
COD_DEPARTAMENTO			  VARCHAR(10) NOT NULL,
ASIG_COD_COORDINACION	  VARCHAR(10) NOT NULL,
ASIG_CREDITOS				    NUMERIC(2) NOT NULL
);

CREATE TABLE DEPARTAMENTO(
CODIG_DEPARTAMENTO		VARCHAR(12) NOT NULL,
DEP_NOMBRE            VARCHAR(30) NOT NULL,
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(CODIG_DEPARTAMENTO)
);

CREATE TABLE ESPECIALIZACION(
CODIG_ESPECIALIZACION		VARCHAR(12) NOT NULL,
NRO_ASIG_BASICA				NUMERIC(2) NOT NULL,
NRO_ASIG_COMPLEMENTARIA		NUMERIC(2) NOT NULL,
NRO_ASIG_ESPECIALIZACION	NUMERIC(2) NOT NULL,
NRO_SEMINARIOS				NUMERIC(2) NOT NULL,
COD_DEPARTAMENTO			VARCHAR(10) NOT NULL,
NOMBRE_AREA					VARCHAR(60) NOT NULL,
CONSTRAINT PK_AREA PRIMARY KEY(CODIG_ESPECIALIZACION)
);

CREATE TABLE AREA(
NOMBRE_AREA					VARCHAR(60) NOT NULL,
CONSTRAINT PK_AREA PRIMARY KEY(NOMBRE_AREA)
);

CREATE TABLE COMPONENTE(
COMP_NOMBRE					VARCHAR(12) NOT NULL,
COMP_CREDITOS				NUMERIC(2) NOT NULL,
COMP_DESCRIPCION    VARCHAR(1000),
CONSTRAINT PK_COMPONENTE PRIMARY KEY(COMP_NOMBRE)
);

CREATE TABLE PERTENECE(
COD_ASIG 			VARCHAR(12) NOT NULL,
COD_DEPARTAMENTO 	NUMERIC(4) NOT NULL,
COMP_NOMBRE			VARCHAR(30) NOT NULL,
NOMBRE_AREA			VARCHAR(60) NOT NULL,
CONSTRAINT PK_PERTENECE PRIMARY KEY (COD_ASIG, COD_DEPARTAMENTO, COMP_NOMBRE, NOMBRE_AREA)
);


CREATE DEPERTAMENTO (
